version: '3.8'

services:
  frontend:
    hostname: frontend
    image: covapp.azurecr.io/frontend
    ports: 
      - 3000:3000
    env_file:
      - ./frontend/.env
    

  # API Services
  auth-service:
    hostname: auth-service
    image: covapp.azurecr.io/auth_service
    ports:
      - 8000:8000
    env_file:
      - ./services/auth/.env
    depends_on:
      - auth-db

  auth-db:
    image: postgres:14.1-alpine3.15
    hostname: auth-db
    ports:
      - 5432:5432
    env_file:
      - ./services/auth/.env

  products-service:
    hostname: products-service
    image: covapp.azurecr.io/products_service 
    ports:
      - 8001:8001
    env_file:
      - ./services/products/.env
    depends_on:
      - products-db

  products-db:
    image: postgres:14.1-alpine3.15
    hostname: products-db
    ports:
      - 5433:5432
    env_file:
      - ./services/products/.env

  search-service:
    image: covapp.azurecr.io/serach_service 
    ports:
      - 9000:9000
    hostname: search-service
    env_file:
      - ./services/search/.env
    depends_on:
      - search-db

  search-consumer:
    image: covapp.azurecr.io/serach_service 
    env_file:
      - ./services/search/.env
    environment:
      - IS_CONSUMER=1
    depends_on:
      - search-db

  search-db:
    image: mongo:4.4.4
    container_name: search-db
    hostname: search-db
    ports:
      - 27017:27017
    volumes:
      - 'db_data:/data/db'
      - 'db_config:/data/configdb'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: test


volumes:
  postgres_data:
  db_data:
  db_config:
