apiVersion: v1
kind: Secret
metadata:
  name: auth
type: Opaque
stringData:
  DJANGO_PORT: "8000" # 8000
  POSTGRES_HOST: auth-db.default.svc.cluster.local
  POSTGRES_PORT: "5432"
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: users
