apiVersion: v1
kind: Secret
metadata:
  name: product
type: Opaque
stringData:
  FASTAPI_PORT: "8001" # "8001"
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: products-db.default.svc.cluster.local
  POSTGRES_PORT: "5432"
  POSTGRES_DB: products
  RABBITMQ_URL: amqps://ynoocxhb:sOXZG6xEDo1tNtJBszctir1cW9PARTa5@beaver.rmq.cloudamqp.com/ynoocxhb
  DATABASE_URL: postgresql+asyncpg://postgres:postgres@products-db.default.svc.cluster.local:5432/postgres
  AUTH_SERVICE_BASE_URL: http://auth-service.default.svc.cluster.local
