apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongo-db-volume
provisioner: disk.csi.azure.com
parameters:
  skuName: Standard_LRS
  location: eastus
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

